# Generated by Django 4.2.7 on 2024-01-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
