# Generated by Django 4.2.7 on 2024-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_orderhistory_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='all_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
