# Generated by Django 4.2.7 on 2024-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_orderhistory_all_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowercategories',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowercategories',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
